kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: google-com-website
  namespace: monitoring
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
      - http://google.com